### ISSUE TITLE
try out https://godoc.org/github.com/cznic/cc#Parse

### ISSUE THREAD

**Issue by mjibson** [mjibson/moggio#50]
for the vorbis and spc decoders

**Comment by mjibson** [comment]
The following program, with stb_vorbis.c saved as vorbis.c and the stdio.h include disabled, yields a panic.

```
package main

import (
	"fmt"
	"log"

	"github.com/cznic/cc"
)

func main() {
	m := cc.Model{
		Items: map[cc.Kind]cc.ModelItem{
			cc.Ptr:               {8, 8, 8, nil},
			cc.UintPtr:           {8, 8, 8, nil},
			cc.Void:              {0, 1, 1, nil},
			cc.Char:              {1, 1, 1, nil},
			cc.SChar:             {1, 1, 1, nil},
			cc.UChar:             {1, 1, 1, nil},
			cc.Short:             {2, 2, 2, nil},
			cc.UShort:            {2, 2, 2, nil},
			cc.Int:               {4, 4, 4, nil},
			cc.UInt:              {4, 4, 4, nil},
			cc.Long:              {8, 8, 8, nil},
			cc.ULong:             {8, 8, 8, nil},
			cc.LongLong:          {8, 8, 8, nil},
			cc.ULongLong:         {8, 8, 8, nil},
			cc.Float:             {4, 4, 4, nil},
			cc.Double:            {8, 8, 8, nil},
			cc.LongDouble:        {8, 8, 8, nil},
			cc.Bool:              {1, 1, 1, nil},
			cc.FloatComplex:      {8, 8, 8, nil},
			cc.DoubleComplex:     {16, 16, 16, nil},
			cc.LongDoubleComplex: {16, 16, 16, nil},
		},
	}
	t, err := cc.Parse("", []string{"vorbis.c"}, &m)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(t)
}
```

```
panic: internal error

goroutine 1 [running]:
panic(0x5aca80, 0xc820372780)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cznic/cc.(*ctype).isCompatible(0xc820383200, 0xc820369140, 0x498900)
	/go/src/github.com/cznic/cc/etc.go:539 +0x317
github.com/cznic/cc.(*ctype).CanAssignTo(0xc820383200, 0x7f16b022f4f0, 0xc820369140, 0x0)
	/go/src/github.com/cznic/cc/etc.go:624 +0x264
github.com/cznic/cc.(*Expression).eval(0xc820384840, 0xc8201f0400, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cznic/cc/ast2.go:1369 +0x10245
github.com/cznic/cc.(*ExpressionList).eval(0xc820282280, 0xc8201f0400, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cznic/cc/ast2.go:1460 +0x9d
github.com/cznic/cc.yyParse(0x7f16b022f638, 0xc8201f0400, 0xc820014660)
	/go/src/github.com/cznic/cc/parser.go:2822 +0xb187
github.com/cznic/cc.Parse(0x0, 0x0, 0xc82000a680, 0x1, 0x1, 0xc82009c140, 0x0, 0x0, 0x0, 0x23e, ...)
	/go/src/github.com/cznic/cc/cc.go:304 +0xa46
main.main()
	/go/src/github.com/mjibson/moggio/t/main.go:38 +0xde7
exit status 2
```

**Comment by cznic** [comment]
Please [report the issue](https://github.com/cznic/cc/issues/new) with a reproduction case/details/files, such that I can prepare it locally. Thank you.

**Comment by cznic** [comment]
`stb_vorbis.c` now parses at my machine ok. Please take another look, thank you.

**Comment by cznic** [comment]
```
(16:30) jnml@r550:~/src/tmp/20160404$ cat main.go 
package main

import (
	"flag"
	"fmt"
	"go/scanner"
	"os"

	"github.com/cznic/cc"
)

var m = cc.Model{
	Items: map[cc.Kind]cc.ModelItem{
		cc.Ptr:               {8, 8, 8, nil},
		cc.UintPtr:           {8, 8, 8, nil},
		cc.Void:              {0, 1, 1, nil},
		cc.Char:              {1, 1, 1, nil},
		cc.SChar:             {1, 1, 1, nil},
		cc.UChar:             {1, 1, 1, nil},
		cc.Short:             {2, 2, 2, nil},
		cc.UShort:            {2, 2, 2, nil},
		cc.Int:               {4, 4, 4, nil},
		cc.UInt:              {4, 4, 4, nil},
		cc.Long:              {8, 8, 8, nil},
		cc.ULong:             {8, 8, 8, nil},
		cc.LongLong:          {8, 8, 8, nil},
		cc.ULongLong:         {8, 8, 8, nil},
		cc.Float:             {4, 4, 4, nil},
		cc.Double:            {8, 8, 8, nil},
		cc.LongDouble:        {8, 8, 8, nil},
		cc.Bool:              {1, 1, 1, nil},
		cc.FloatComplex:      {8, 8, 8, nil},
		cc.DoubleComplex:     {16, 16, 16, nil},
		cc.LongDoubleComplex: {16, 16, 16, nil},
	},
}

func main() {
	flag.Parse()
	if flag.NArg() != 1 {
		fmt.Fprintf(os.Stderr, "expected one argument, path to stb_vorbis.c\n")
		os.Exit(1)
	}

	predefined, includePaths, sysIncludePaths, err := cc.HostConfig()
	translationUnit, err := cc.Parse(
		predefined+`
#define __PRETTY_FUNCTION__ __func__
#define __attribute__(x)
#define __builtin_va_list void*
#define __const const
#define __extension__
#define __restrict restrict

void* __builtin_alloca(int);
`,
		[]string{flag.Arg(0)},
		&m,
		cc.IncludePaths(includePaths),
		cc.SysIncludePaths(sysIncludePaths),
		cc.EnableIncludeNext(),
		cc.EnableAlternateKeywords(),
		cc.EnableAsm(),
	)
	if err != nil {
		scanner.PrintError(os.Stderr, err)
		os.Exit(1)
	}
	_ = translationUnit
}
(16:30) jnml@r550:~/src/tmp/20160404$ go build
(16:30) jnml@r550:~/src/tmp/20160404$ ./20160404 ~/src/github.com/nothings/stb/stb_vorbis.c && echo ok
ok
(16:30) jnml@r550:~/src/tmp/20160404$ 
```

HTH ;-)
