### ISSUE TITLE
Message too big

### ISSUE THREAD

**Issue by andreaskoch** [mjibson/moggio#52]
I just added my local music folder and after moggio was ready reading all files I got the following error message:

```
2016/03/09 20:51:06 server.cmdRemoveInProgress
2016/03/09 20:51:06 server.cmdProtocolAddInstance
2016/03/09 20:51:07 server.cmdDoSave
2016/03/09 20:51:09 gob: encoder: message too big
goroutine 5 [running]:
github.com/mjibson/moggio/server.printErr(0x7fabea8c0028, 0xc8748e8010)
	/go/src/github.com/mjibson/moggio/server/server.go:42 +0x134
github.com/mjibson/moggio/server.(*Server).commands.func3(0x7fabea8c0028, 0xc8748e8010)
	/go/src/github.com/mjibson/moggio/server/control.go:41 +0x46
github.com/mjibson/moggio/server.(*Server).commands.func25()
	/go/src/github.com/mjibson/moggio/server/control.go:417 +0x56
github.com/mjibson/moggio/server.(*Server).commands(0xc820096b40)
	/go/src/github.com/mjibson/moggio/server/control.go:714 +0x1a99
created by github.com/mjibson/moggio/server.New
	/go/src/github.com/mjibson/moggio/server/server.go:201 +0x4ad
```

I suspect that I have too many music files in the specified folder, but I just wanted to let you know.

**Comment by mjibson** [comment]
How many music files are in that directory? The save file size limit is 1GB, and not currently configurable . This needs to get fixed.

**Comment by andreaskoch** [comment]
Ok. That explains it. The folder is way past 1GB - I cannot check it now
how many files there are but it's about 80 GB.

**Comment by mjibson** [comment]
It's not the size of the folder, it's the size of the save file. The save file contains metadata about the folder. File names, ID3 info, etc. If that is above 1GB, it fails. Number of songs is the most interesting information.

**Comment by andreaskoch** [comment]
Ah OK. It's about 18000 files.
